# Generated by Django 4.2.3 on 2023-08-19 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPlayer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryType', models.CharField(choices=[('TANK', 'Танк'), ('HEALS', 'Хиллеры'), ('DD', 'ДД'), ('SELLER', 'Продавец'), ('GILD_MASTER', 'Гилдмастер'), ('QUEST_GAME', 'Квестигры'), ('BLACKSMITH', 'Кузнец'), ('TANNER', 'Кожевник'), ('POTION_MASTER', 'Зельевары'), ('SPELL_MASTER', 'Мастер заклинаний')], default='SELLER', max_length=32)),
                ('datePub', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bboard.player')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.category')),
                ('postThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('commentCreation', models.DateTimeField(auto_now_add=True)),
                ('commentPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.player')),
                ('commentPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.post')),
            ],
        ),
    ]
